### PR TITLE
Move Continuous Integration to Github Actions and be able to download resulting binaries

### PR DESCRIPTION
**Pull request by thepapermen**
@ricki-z, hi, thanks for making The World a better place.

I saw that CI for this project got broken and see GitHub Actions as a nice a somewhat more user friendly of Continuous Integration. You can **[see the result here.](https://github.com/thepapermen/airrohr-firmware-flasher/actions/runs/4996606565)**

As I've written before, I've encountered an issue with and Ubuntu build of this great tool, since I fixed it, **I automated the build in the cloud for all of the supported platforms.** To be able to Support Mac OS 11, I had to bump some of requirement packages versions a bit and also add a small compatibility shim in `dmgbuild_settings.`

This will allow to test different OSes, Python versions and configs more easily.
Screenshot from 2023-05-16 22-59-03

I have written a github action code to automatically build the airrohr-firmware-flasher on Linux (Ubuntu 20.04 and [Ubuntu 22.04),](https://github.com/opendata-stuttgart/airrohr-firmware-flasher/issues/61) Mac OS (11) and Windows. 

All of the CI code is in one single file: https://github.com/thepapermen/airrohr-firmware-flasher/blob/master/.github/workflows/build-airrohr-firmware-flasher.yml

**The build runs and produces executable files. Hovever, I didn't  test and run the resulting binaries except the Ubuntu 20.04 version because I don't have PCs running other OSes than that.**

### CODE REVIEW

**Comment by ricki-z** [comment]
Sorry for the delay. BUt I had problems to get all needed test VMs running ...

**Comment by thepapermen** [comment]
Thank you for your work, it helps thousands of people to keep better health.

**Comment by JPHNL** [comment]
Hello, I am new on this platform and trying to build a particulate matter sensor. I use a brand-new MacBook Air on Sonoma 14.1.2. On this system the “Sensor.Community Airrohr Flasher” does not run. Is it possible to run the flasher on Mac? Thanks for the help!

**Comment by thepapermen** [comment]
@JPHNL, if you clone the repo I think you will be able to download the MacOS binary in the "Actions" tab of it.

**Pull request merged**
